name = "Big"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dff21f1929fbce81e4747aa9a82b353b09c12d64090c1b9436b30dde86b9c97"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
